# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- dev/olegoid/imageupload
pr: none
pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    pip install twine
    pip install build
  displayName: 'Install Twine and Build'

- script: |
    python -m build -w
  displayName: 'Run build'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: blue-cardigans/python-private-feed
  displayName: 'Authenticate Twine'

- script: |
    python -m twine upload -r python-private-feed --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload'
